services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dicom_portal
      POSTGRES_USER: dicom
      POSTGRES_PASSWORD: dicom
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  orthanc:
    image: jodogne/orthanc-plugins
    # Apple Silicon 若遇到 platform warning，可打開下一行：
    # platform: linux/amd64
    command: ["/etc/orthanc/orthanc.json"]
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - orthanc_data:/var/lib/orthanc/db
    ports:
      - "4242:4242"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-dicom.json:/opt/keycloak/data/import/realm-dicom.json:ro
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://dicom:dicom@postgres:5432/dicom_portal
      ORTHANC_URL: http://orthanc:8042
      ORTHANC_USERNAME: orthanc
      ORTHANC_PASSWORD: orthanc
      KEYCLOAK_ISSUER: http://localhost:8080/realms/dicom
      KEYCLOAK_ALLOWED_ISSUERS: http://localhost:8080/realms/dicom,http://192.168.1.112:8080/realms/dicom
      KEYCLOAK_JWKS_URL: http://keycloak:8080/realms/dicom/protocol/openid-connect/certs
      KEYCLOAK_CLIENT_ID: dicom-portal
      KEYCLOAK_AUDIENCE: dicom-portal-api
      TENANT_CLAIM: tenant_id
      CORS_ORIGIN: http://localhost:8088
      OHIF_VIEWER_URL: http://localhost:3000/viewer
    depends_on:
      - postgres
      - orthanc
      - keycloak
    ports:
      - "8000:8000"

  ohif:
    image: ohif/viewer:latest
    volumes:
      - ./ohif/index.html:/usr/share/nginx/html/index.html:ro
      - ./ohif/app-config.js:/usr/share/nginx/html/app-config.js:ro
    depends_on:
      - orthanc
      - frontend
    ports:
      - "3000:80"

  frontend:
    image: nginx:1.27-alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - orthanc
    ports:
      - "8088:80"
      - "8042:8042"
      - "5601:5601"

volumes:
  postgres_data:
  orthanc_data:
